spring.application.name=ems1

server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/userems?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Pratheek@101
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pratheekj62@gmail.com
spring.mail.password=asxm knnw cjsv zrhy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true